# This file is machine-generated - editing it directly is not advised

julia_version = "1.13.0-beta1"
manifest_format = "2.1"
project_hash = "c479309fc6f9ef2edf079fff566a93c586f725e3"

[[deps.StringViews]]
path = "."
uuid = "354b36f9-a18e-4713-926e-db85100087ba"
version = "1.3.6"
